### ISSUE TITLE
RN Project fails to run when this lib is a dep

### ISSUE THREAD

**Issue by dcworldwide** [stoffern/gl-react-imagefilters#1]
Hi @stoffern, I get an error when trying to run my RN project after installing this lib as a dep. I think it is because react is included as a dep instead of a peer dep.

**Comment by st0ffern** [comment]
@dcworldwide what is your error message?
What platform?

**Comment by rgovindji** [comment]
Ran into the same issue:
-     "react-native": "^0.28.0",
-     "react": "^15.1.0",
-     "gl-react": "^2.2.5",
-     "gl-react-image": "0.0.2",
-     "gl-react-instagramfilters": "^0.1.0",
-     "gl-react-native": "^2.28.0",

```
`Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ViewportMetrics
  Paths: /Users/rgovindji/Projects/Bunch/node_modules/react/lib/ViewportMetrics.js collides with /Users/rgovindji/Projects/Bunch/node_modules/gl-react-imagefilters/node_modules/react/lib/ViewportMetrics.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: ViewportMetrics
  Paths: /Users/rgovindji/Projects/Bunch/node_modules/react/lib/ViewportMetrics.js collides with /Users/rgovindji/Projects/Bunch/node_modules/gl-react-imagefilters/node_modules/react/lib/ViewportMetrics.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/rgovindji/Projects/Bunch/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /Users/rgovindji/Projects/Bunch/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25
    at process._tickCallback (internal/process/next_tick.js:103:7)
~
Process terminated. Press <enter> to close the window`
```

**Comment by st0ffern** [comment]
Tnx for log. 
Please try out the new version, this should fix the problem. 1bbff5e12ba0ae13bcb65771eaa1f8f8fff7a20e
Remember to rm `node_modules` and do a fresh `npm i`

let me know if it works out

**Comment by rgovindji** [comment]
Thanks I'll try it out tonight!

**Comment by st0ffern** [comment]
@rgovindji btw if you are using node v4, i would recommend to switch to v6. 
They will switch from v4 to v6 the 1. October anyways :wink:

**Comment by rgovindji** [comment]
Still having a bit of an issue I can't resolve the module.  Here is my import statement:

`import {ImageFilter} from 'gl-react-imagefilters';`

Also the one in the example readme might be incorrect, are you missing an "s" at the end of "gl-react-imagefilter". I tried with an "s" and without and still the same error below.

```
var ImageFilter = require("gl-react-imagefilter").ImageFilter;
// or
import {ImageFilter} from "gl-react-imagefilter";

```

![screen shot 2016-08-16 at 11 09 59 am](https://cloud.githubusercontent.com/assets/251495/17704143/18549e02-63a2-11e6-8998-31951e8933ff.png)

**Comment by st0ffern** [comment]
@rgovindji my bad. it is working now..
dist was missing in the NPM release, added .npmignore that should fix it! :wink: 
https://github.com/stoffern/gl-react-imagefilters/commit/50cc5010

readme updated to it should be `gl-react-imagefilters`

**Comment by rgovindji** [comment]
Sweet thanks for the quick fix! 👍

**Comment by st0ffern** [comment]
Np

**Comment by rgovindji** [comment]
@stoffern I thought it was fixed on my end but I'm getting this error now actually. It may not be caused by this library but this is what I am seeing.

<img width="279" alt="screen shot 2016-08-16 at 10 04 03 pm" src="https://cloud.githubusercontent.com/assets/251495/17722110/ae4eadf2-63fd-11e6-96ba-42732da427bb.png">

```
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at declareOpts.js:60:13
    at index.js:241:20
    at tryCallOne (/Users/rgovindji/Projects/Bunch/node_modules/promise/lib/core.js:37:12)
    at /Users/rgovindji/Projects/Bunch/node_modules/promise/lib/core.js:123:15
    at flush (/Users/rgovindji/Projects/Bunch/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by st0ffern** [comment]
@rgovindji this is not the library.
Just testet it here and it is working fine, can you show me the code of PhotoEditPage?
There is a parameter that is passed in one component that is supposed to be a string...

**Comment by rgovindji** [comment]
Sure it's very basic

```
export default class PhotoEditPage extends Component {
  constructor(props, context) {
    super(props, context);

  }

  render() {
    return (
      <View style={styles.container}>
        <Surface width={300} height={200}>
          <ImageFilter sepia={3} blur={2}>
            <GLImage
                 source="https://unsplash.it/200/300"
                imageSize={{ width: 300, height: 200 }}
                 resizeMode="cover" />
          </ImageFilter>
        </Surface>
      </View>
    );
  }
```

**Comment by st0ffern** [comment]
@rgovindji try doing 

``` js
import ImageFilter from 'gl-react-imagefilters'
```

**Comment by rgovindji** [comment]
YUP! that did it :)
